// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MetricGetter is an autogenerated mock type for the metricGetter type
type MetricGetter struct {
	mock.Mock
}

// GetAllMetrics provides a mock function with given fields:
func (_m *MetricGetter) GetAllMetrics() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetCounter provides a mock function with given fields: _a0
func (_m *MetricGetter) GetCounter(_a0 string) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGauge provides a mock function with given fields: _a0
func (_m *MetricGetter) GetGauge(_a0 string) (float64, error) {
	ret := _m.Called(_a0)

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMetricGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMetricGetter creates a new instance of MetricGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMetricGetter(t mockConstructorTestingTNewMetricGetter) *MetricGetter {
	mock := &MetricGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
